### ISSUE TITLE
Another approach on pretty uri

### ISSUE THREAD

**Issue by wg-daniel** [facundoolano/jorge#35]
Hello :wave: 

First of all, I really enjoy setting up my new blog with jorge. It's really simple to work with and to integrate into a CI job.

One of the things I encountered was the pretty uri not working on static hosts like github or sourcehut pages.

As there is no way to apply the recommended nginx config as explained in your tutorial, I solved it like this as a post build fix.

```sh
echo "Hotfixing directory blog names"
cd target/blog
for file in *; do
    if [[ $file != "index.html" ]]; then
        mkdir "${file%.*}"
        mv "$file" "${file%.*}/index.html"
    fi
done
```

Which essentially creates a directory based on the filename and then moves that file into it renaming it to index.

Might be an interesting approach to make the project a friendlier to use on the generic static hosts out there.

Anyhow, thanks for your work on jorge!

**Comment by facundoolano** [comment]
Thanks for reporting, I wasn't aware of this restriction (although it makes sense, I did need to manually implement it for the local server).

I guess I could just default to always adding the extra wrapper directory when generating a page at the target. And then I could drop the special code in the nginx setup and the local file server.

**Comment by facundoolano** [comment]
@wg-daniel opened [a PR](#42) with this change, in case you want to try it out.
