### ISSUE TITLE
Expose post.content as a template variable in addition to post.excerpt

### ISSUE THREAD

**Issue by ILoveLinux666** [facundoolano/jorge#40]
Hello,
Thank you for writing this nice org mode ssg. I have a question.
Is it possible to embed full post content in the description portion of feed.xml? From what I've read in the docs only _post.excerpt_ is exposed, not _post.content_ for example. It would allow the user to read the post without having to leave their rss reader.

**Comment by facundoolano** [comment]
post.content is not currently exposed but it should, I'll add it in my next round of updates to this project.

**Comment by facundoolano** [comment]
@ILoveLinux666 opened a PR with the update, do you mind trying it out and see if it works as you expected?

**Comment by ILoveLinux666** [comment]
I believe it works!! I need to tweak the feed.xml to represent the new paragraphs and formatting stuff better, but the post.content works. Thank you! I will also try out #42 because i host my website on an openbsd vps using httpd and had to implement a workaround for a similar issue.

**Comment by ILoveLinux666** [comment]
Also I noticed that the xmlns="http://www.w3.org/2005/Atom" property for the feed tag gets removed when the feed is build. According to the atom standard [wikipedia](https://en.wikipedia.org/wiki/Atom_(web_standard)#Atom_1.0_and_IETF_standardization) it should be present. I hope I'm not to nitpicky 🥺.

**Comment by facundoolano** [comment]
> Also I noticed that the xmlns="http://www.w3.org/2005/Atom" property for the feed tag gets removed when the feed is build. According to the atom standard [wikipedia](https://en.wikipedia.org/wiki/Atom_(web_standard)#Atom_1.0_and_IETF_standardization) it should be present. I hope I'm not to nitpicky 🥺.

Can you give me some steps to reproduce that, target/feed.xml looks ok
```
<?xml version="1.0" encoding="utf-8"?><feed xmlns="http://www.w3.org/2005/Atom"> ...
```

**Comment by facundoolano** [comment]
> I will also try out #42 because i host my website on an openbsd vps using httpd and had to implement a workaround for a similar issue.

Let me know how it goes, I'll merge the PR and publish a new version afterwards.
