### ISSUE TITLE
Footnotes in Markdown

### ISSUE THREAD

**Issue by libresoul** [facundoolano/jorge#45]
I recently noticed that footnotes I have included in my markdown files aren't showing in jorge. I was using the generic way of inserting footnotes like '[^1]'. Is there a different method to insert footnotes or is it not supported at the moment?

**Comment by facundoolano** [comment]
Hi @libresoul . It seems like I need to enable footnotes in the code as a [goldmark extension](https://github.com/yuin/goldmark?tab=readme-ov-file#footnotes-extension). I'll look into it.

**Comment by libresoul** [comment]
@facundoolano oh thank you very much.

**Comment by facundoolano** [comment]
@libresoul just published a new version with footnote support (plus tables and strike-through which were also disabled).
