### ISSUE TITLE
[FYI] Now available from ArchLinux User Repository (AUR)

### ISSUE THREAD

**Issue by kseistrup** [facundoolano/jorge#52]
[ This “issue” is purely informational, you may close it at your discretion. ]

I thought you would like to know that `jorge` is now available from [AUR](https://aur.archlinux.org/packages/jorge-git):

* https://aur.archlinux.org/packages/jorge-git

It will compile `jorge` from the latest git commit, and install it along with the LICENSE and the README.

It can be installed easily with an [AUR helper](https://wiki.archlinux.org/title/AUR_helpers), e.g. `yay`:

```sh
$ yay -S jorge
$ # or
$ yay -S jorge-git
```

:pray:

**Comment by facundoolano** [comment]
Nice, if you want you can send a PR adding this installation method to the README.
